nofrixion/moneymoov-dotnet

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs

Aaron tried a full PISP payment on production and the status was set to Authorized. In this case, it should have redirected to result page when the payment link is opened again. But it loaded the payelement instead. This was caused because of incorrect outstanding amount calculation. The Yapily webhook event logged had amount as 0. Turns out we were not logging the amount for PIS webhooks.
In this change, I am considering events with amount > 0 only. Although, I have made changes in the event logging to log the amount as well.

Incorrect outstanding amount in case of PISP authorized status

---

src/NoFrixion.MoneyMoov/Models/Merchant/MerchantPayByBankSetting.cs

Removed Feature, ProviderID and AccountType properties from the PayByBankSettings and added PersonalInstitutionID and BusinessInstitutionID fields for the next-gen PayElement.

[MOOV-1617]: Added Personal and Business Bank Institution IDs

---

src/NoFrixion.MoneyMoov/Models/Merchant/MerchantPayByBankSetting.cs

Added a bank message image URL field to be used when displaying a bank option on the PayElement.

[MOOV-1624]: Added bank message image field for the PayElement

---

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestUpdate.cs

Needs to be set automatically to give us the best chance of matching up the payment request and payin.

Obsolete PISP reference. 

---

src/NoFrixion.MoneyMoov/Enums/PaymentRequestEventTypesEnum.cs

New payment request event type "pisp_refund" when a payment request with PIS is refunded.

pisp_refund event type

---

src/NoFrixion.MoneyMoov/Constants/PaymentRequestConstants.cs

The hyphens do not need to be escaped in these two cases. BUT we've had bugs introduced when characters have been added that turn the - into a range and then it does need to be escaped. This was the same bug we had on the identity server and special password chars.
Rule is always escape - as \- if it's being used to match a single char.

Fixed regexes for payment request update

---

src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs
test/MoneyMoov.UnitTests/Models/PaymentRequestExtensionTests.cs

Payment attempts for card_sale was not being recorded properly. Hosted page results use attempts for partial payments.

Payment attempt card sale fix

---

src/NoFrixion.MoneyMoov/Extensions/PaymentRequestEventExtensions.cs
src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentAttempt.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs
test/MoneyMoov.UnitTests/Models/PaymentRequestEventExtensionsTests.cs
test/MoneyMoov.UnitTests/Models/PaymentRequestExtensionTests.cs
test/MoneyMoov.UnitTests/Models/PaymentRequestResultTests.cs

1. Update Payment request result logic to use Card payment attempts.
2. Added CardAuthorisedAmount to PaymentAttempts to differentiate it from Pisp AuthorisedAmount as they are completely different.
3. SettledAmount is solely for pisp and CaptureAttempts collection is for cards. This differentiation is necessary because it can get confusing as they mean completely different things.
4. Wrote new test cases and updated existing ones. Integration tests are already written for this.

Using card payment attempts in Payment Request result

---

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestEvent.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestUpdate.cs

> Add FailureCallbackUrl to payment request event models. 
> Add OriginUrl to payment request event model.

Add two model properties to improve handling of pay by bank failures

---

src/NoFrixion.MoneyMoov/Enums/PaymentRequestEventTypesEnum.cs
src/NoFrixion.MoneyMoov/Extensions/PaymentRequestEventExtensions.cs
src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs
src/NoFrixion.MoneyMoov/Extensions/PaymentRequestPaymentAttemptExtensions.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/CardPaymentResponseStatus.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentAttempt.cs
test/MoneyMoov.UnitTests/Extensions/PaymentRequestPaymentAttemptExtensionsTests.cs

Added extension methods for PaymentRequestPaymentAttempt to calculate amount available to refund and void. Introduced a flag in refund attempts to differentiate between card refund and void.
Also, added a new event type called card_refund to differentiate between card voids and refunds.

Added extension methods 

---

src/NoFrixion.MoneyMoov/Enums/PaymentProcessorsEnum.cs
src/NoFrixion.MoneyMoov/NoFrixionProblem.cs
src/NoFrixion.MoneyMoov/RestClient/RestApiClient.cs
src/NoFrixion.MoneyMoov/RestClient/RestApiResponse.cs

Add two payment processors to differentiate between BC standard and agency banking.
Add raw error property to NoFrixionProblem for cases where the error contents don't match the expected model.

Additional payment processor and enhancements to REST response

---

src/NoFrixion.MoneyMoov/Extensions/StringExtensions.cs
src/NoFrixion.MoneyMoov/Mapping/CsvMapper.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestEmailNotification.cs
test/MoneyMoov.UnitTests/Models/PaymentRequestEmailNotificationTests.cs

A need arose to use both the payment request AND csv result variables in teh email template.

Adjust the string substitution logic for payreq email notifications

---

src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs

Added source account balance field to payout model to render it on the Identity Server's single-payout approval screen.

[MOOV-2291]: Added source account balance field to payout model

---

src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutUpdate.cs

Add can update and can authorise flags to give user an indication of available actions.

Add Bitcoin fee fields to payout models.

---

src/NoFrixion.MoneyMoov/Models/Payouts/PayoutUpdate.cs

We will need to change or improve our field mapper update approach soon as it cannot deal with nested objects.

Adjusted payout update model to allow updating of Bitcoin address.

---

src/NoFrixion.MoneyMoov/Enums/BeneficiaryEventTypeEnum.cs
src/NoFrixion.MoneyMoov/Models/Beneficiary/BeneficiaryEvent.cs

In the beneficiary authorisation process, if a beneficiary has been updated, it has to be re-authorised. 
There is a separate design for Authorisation page for updated beneficiary in identity server. In order to implement that, we need to know which properties were updated to add the "Updated" tag beside it. 
Hence, this PR adds all the beneficiary details in the events so a history of update is available which can be used in the identity server.

Added beneficiary details to event

---

src/NoFrixion.MoneyMoov/Models/Beneficiary/BeneficiaryUpdate.cs

Changed the type of AccountID in BeneficiaryUpdate model from Guid to string. This is done so the user can switch a beneficiary from Merchant level to account level. Let's say a beneficiary was created with AccountID which is account level. Now, the AccountID needs to be removed so the beneficiary is available at the merchant level. If an empty string is passed then the AccountID will be removed if present. And if it is null then the user does not intend to do anything to the AccountID. If it is set to a different AccountID then it will get updated.

Changed AccountID type from Guid to string.

---

src/NoFrixion.MoneyMoov/Models/Payruns/PayrunInvoice.cs

This PR addresses am issue where a duplicated 'Subtotal' property in the `PayrunInvoice` class was causing a 500 error in the API. The error was identified during API calls involving the `PayrunInvoice` data structure.
- **Removed Duplicated 'Subtotal' Property**: Identified and removed the redundant 'Subtotal' property from the `PayrunInvoice` class. This duplication was leading to serialization issues and resulting in a 500 error during API responses.

Remove Duplicate `Subtotal` Property in `PayrunInvoice` Class

---

src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutUpdate.cs

- Updated PayoutCreate, PayoutUpdate to use BeneficiaryID instead of BeneficiaryIdentifierID.
- Added Beneficiary in the Payout model.

Updated PayoutCreate, PayoutUpdate to use BeneficiaryID instead of BeneficiaryIdentifierID

---

src/NoFrixion.MoneyMoov/Mapping/AccountIdentifierMappers.cs
src/NoFrixion.MoneyMoov/Mapping/CounterpartyMappers.cs
src/NoFrixion.MoneyMoov/Models/Account/AccountIdentifier.cs
src/NoFrixion.MoneyMoov/Models/Account/AccountIdentifierCreate.cs
src/NoFrixion.MoneyMoov/Models/Account/CounterpartyCreate.cs
src/NoFrixion.MoneyMoov/Models/Beneficiary/Beneficiary.cs
src/NoFrixion.MoneyMoov/Models/Beneficiary/BeneficiaryCreate.cs
src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutUpdate.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutsValidator.cs
src/NoFrixion.MoneyMoov/Models/Rules/RuleActions/SweepDestination.cs
src/NoFrixion.MoneyMoov/NoFrixion.MoneyMoov.csproj
test/MoneyMoov.UnitTests/Mapping/AccountIdentifierMapperTests.cs
test/MoneyMoov.UnitTests/Mapping/CounterpartyMapperTests.cs
test/MoneyMoov.UnitTests/Models/AccountIdentifierTests.cs
test/MoneyMoov.UnitTests/Models/BeneficiarySerialisationTests.cs
test/MoneyMoov.UnitTests/Models/BeneficiaryValidationTests.cs
test/MoneyMoov.UnitTests/Models/PayoutsValidatorTests.cs
test/MoneyMoov.UnitTests/Models/RuleValidationTests.cs

- Made currency property in AccountIdentifier model as required.
- Added AccountIdentifierCreate and CounterpartyCreate models to be used in PayoutCreate and BeneficiaryCreate models for backward compatibility.
- Added mappers for new models. If currency is passed in the create models, it is given priority but if not then, the currency of the parent is set to account identifier.

Added AccountIdentifierCreate and CounterpartyCreate model. 

---

src/NoFrixion.MoneyMoov/Enums/MerchantTokenPermissionsEnum.cs

Used to indicate merchant tokens are not authorised for an operation.

Add deny option for merchant tokens permission enum

---

src/NoFrixion.MoneyMoov/Models/Rules/Rule.cs
src/NoFrixion.MoneyMoov/Models/Transaction/Counterparty.cs

It makes sense for the counterparty to set the identifer details from the AccountID or BeneficiaryID so relocated that validation rule. 
Reduced min interval from 60 minutes to 1 minute.

Moved the mult-dest check from counterparty. 

---

src/NoFrixion.MoneyMoov/Models/Beneficiary/Beneficiary.cs
src/NoFrixion.MoneyMoov/Models/User/UserMinimal.cs

- Added a new UserMinimal model to return basic info about the user that is often required on the MM4B. Didn't want to return the entire User model. If this is not correct, I will return the User model in that case.

Added user minimal model to return authoriser info

---

src/NoFrixion.MoneyMoov/Enums/PayoutEventTypesEnum.cs

Added a payout event type for recording when a payout's beneficiary is enabled. Kind of an infrequent occurrence, but just in case.

MOOV-3289: Added BeneficiaryEnabled Payout event type

---

src/NoFrixion.MoneyMoov/Models/Payruns/PayrunInvoice.cs

Drops the Required requirement (lol) for the Payrun Invoice Reference field.

MOOV-3176: Invoice Reference field is no longer required

---

src/NoFrixion.MoneyMoov/Enums/PayrunEventTypeEnum.cs

Removed Authorised event type as submitted event implies the same.

Removed Authorised event type as submitted event implies the same.

---

src/NoFrixion.MoneyMoov/Mapping/PayrunInvoiceMapper.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutsValidator.cs
src/NoFrixion.MoneyMoov/Models/Payruns/PayrunInvoice.cs
test/MoneyMoov.UnitTests/Models/PayrunInvoiceValidatorTests.cs

Will hopefully avoid the case where an invoice can result in a payout getting created but then fail once submitted to the upstream processor.

Remove invoice specific validaiton logic and use payout validations.

---

src/NoFrixion.MoneyMoov/Enums/PayrunStatus.cs

Added intermediate status for payrun approval. This status indicates tha the pay run approval is in progress and payouts are being created for the pay run.

Added intermediate status for payrun approval.

---

src/NoFrixion.MoneyMoov/Enums/AccountTypeEnum.cs
src/NoFrixion.MoneyMoov/Models/Account/PaymentAccountCreate.cs

- Added a new account type called "Tribe"
- Removed the default "Unknown" account type from enum as the default should be Standard.
- Moved the AccountTypeEnum to MoneyMoov as it is required to be set when creating payment account.
- The payment account create model now has the option to explicitly set the type and also the tribe account id.

New account type Tribe

---

src/NoFrixion.MoneyMoov/RestClient/RestApiClient.cs
src/NoFrixion.MoneyMoov/RestClient/RestApiResponse.cs

Tribe has a different response model which doesn't quite fit in the RestApiResponse we have. We receive the data even in case of non-success response, and the data has the error message. So added a flag to try and deserialise the data even on error response.

Support for receiving data in case of non-success response

---

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestEvent.cs

Added a model prop for Banking Circle's Direct Debit payment reference.

MOOV-3499: Add BC DirectDebitPaymentReference prop

---

src/NoFrixion.MoneyMoov/Extensions/EnumExtensions.cs
src/NoFrixion.MoneyMoov/JsonConverters/NumericConverter.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/IPaymentRequest.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestMinimal.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestUpdate.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestValidator.cs
test/MoneyMoov.UnitTests/Mapping/CsvMapperTests.cs
test/MoneyMoov.UnitTests/Models/PaymentRequestCreateTests.cs
test/MoneyMoov.UnitTests/Models/PaymentRequestEmailNotificationTests.cs
test/MoneyMoov.UnitTests/Models/PaymentRequestResultTests.cs

As discussed in standup falg enums do not play well with swagger and openapi. This PR replaces the flag enum with a List in the public model while keeping the benefits of the flag enum in the biz logic and data entity.

Deprecates the PaymentMethodTypes flag enum property in favour of a List

---

src/NoFrixion.MoneyMoov/Models/Mandates/Mandate.cs
src/NoFrixion.MoneyMoov/Models/Mandates/MandateCreate.cs

Temporarily remove the Amount field from the model. It's not what users expect and we're not using for the moment.

Direct Debit mandate model fix

---

src/NoFrixion.MoneyMoov/Attributes/EmailAddressMultipleAttribute.cs

Allow null, empty or whitespace strings for the remittance email list through the EmailAddressMultiple atttribute.

MOOV-3920: Allow null or whitespace email address list for payruns

---

src/NoFrixion.MoneyMoov/Enums/SharedSecretAlgorithmsEnum.cs
src/NoFrixion.MoneyMoov/HmacSignature/HmacAuthenticationConstants.cs
src/NoFrixion.MoneyMoov/HmacSignature/HmacSignatureAuthHelper.cs
src/NoFrixion.MoneyMoov/HmacSignature/HmacSignatureBuilder.cs
src/NoFrixion.MoneyMoov/HmacSignature/HttpSignatureHeaders.cs
src/NoFrixion.MoneyMoov/Models/Token/TokenAdd.cs
src/NoFrixion.MoneyMoov/RestClient/RestApiClient.cs
test/MoneyMoov.UnitTests/HmacSignature/HmacSignatureAuthHelperTests.cs
test/MoneyMoov.UnitTests/HmacSignature/HmacSignatureBuilderTests.cs

HMACs are already being used in API key authentication and that's now being expanded as an option for merchant tokens. This PR builds on the existing logic to make it flexible enough to deal with both cases.

Expand HMAC functionality

---

src/NoFrixion.MoneyMoov/Enums/PayoutDocumentTypesEnum.cs
src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutDocument.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutDocumentCreate.cs

Added PayoutDocuments collection properties to Payout models.
Also deprecated the payout PayrunInvoices collection properties.

MOOV-3952: Add PayoutDocuments collection props

---

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs

Added Sandbox Direct Debit settlement delay in seconds field to payment request models.

MOOV-4270: Add Sandbox Direct Debit settlement delay seconds field

---

src/NoFrixion.MoneyMoov/Enums/PayrunEventTypeEnum.cs
src/NoFrixion.MoneyMoov/Enums/PayrunStatus.cs

Added new enum values for a processing state for both payrun status and payrun event types.

MOOV-3707: Add Processing payrun state and event type

---

src/NoFrixion.MoneyMoov/Constants/HttpClientConstants.cs
src/NoFrixion.MoneyMoov/Enums/PaymentProcessorsEnum.cs
src/NoFrixion.MoneyMoov/Enums/PaymentRequestEventTypesEnum.cs
src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs
src/NoFrixion.MoneyMoov/Models/Merchant/Merchant.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs
src/NoFrixion.MoneyMoov/Models/Payouts/PayoutsValidator.cs
test/MoneyMoov.UnitTests/Models/PaymentRequestExtensionTests.cs
test/MoneyMoov.UnitTests/Models/PaymentRequestResultTests.cs
test/MoneyMoov.UnitTests/Models/PayoutsValidatorTests.cs
test/MoneyMoov.UnitTests/Models/PayrunInvoiceValidatorTests.cs

Remove modulr code. Have made most properties obsolete instead of removing them as these are public models.

Remove modulr code

---

src/NoFrixion.MoneyMoov/ApiClients/UserInviteClient.cs
src/NoFrixion.MoneyMoov/Models/UserInvite/UserInvite.cs
src/NoFrixion.MoneyMoov/Models/UserInvite/UserInviteCreate.cs

Added a property to UserInvite and UserInviteCreate called InitialRoleID to indicate the initial role assignment for first user of merchant.

One step user role assignment for first user

---

src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs

Use ulong instead of decimal in payout hash to avoid string serialisation discrepancies

---

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestTemplate.cs

Added an enum to specify default fields of payment request. The name and description of these default fields can be handled by the client.

Added a list of default fields to distinguish between default and custom fields.

---

src/NoFrixion.MoneyMoov/Models/Merchant/Merchant.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestMinimal.cs
src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentReceipt.cs

Added new fields for PNG and SVG merchant logos to replace the old way of building the URL with a specific text template and the merchant's short name.

MOOV-4542: Add fields for merchant logos for PNG and SVG

---

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentReceipt.cs

Made customer email address nullable as a receipt can be downloaded by the merchant on demand as well.

Made customer email address nullable

---

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestTemplate.cs

Split the single priority bank property on the payment request template entity to a list, like the destination accounts property.

TRAN-166: Add support for per-currency priority bank on payment request templates

---

src/NoFrixion.MoneyMoov/Extensions/PaymentAmount.cs

Pablo I suggested that we remove the space between the currency symbol and amount.

Removed space in between amount and currency
