nofrixion/moneymoov-dotnet

src/NoFrixion.MoneyMoov/Models/Transaction/Transaction.cs, src/NoFrixion.MoneyMoov/Models/Utils/PageResponse.cs
- Update transaction DTO
- Add page response DTO
=> Update Transaction DTO

src/NoFrixion.MoneyMoov/MoneyMoovApiEndPoints.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
Added user role management API endpoint builder.
=> Added user role API endpoint builder

src/NoFrixion.MoneyMoov/Models/User/User.cs, src/NoFrixion.MoneyMoov/MoneyMoovApiEndPoints.cs
Added merchant Id to user model to be used during new user registration.
=> Added merchant Id to user model to be used during new user registration.

src/NoFrixion.MoneyMoov/Enums/CardTokenCreateEnum.cs
Created an enum for card tokenization modes.
=> Created an enum for card tokenization modes.

src/NoFrixion.MoneyMoov/Enums/PaymentMethodTypeEnum.cs
Added applePay payment method.
=> Added applePay payment method.

src/NoFrixion.MoneyMoov/Api/MerchantClient.cs, src/NoFrixion.MoneyMoov/Api/MoneyMoovApi.cs, src/NoFrixion.MoneyMoov/Api/UserClient.cs, src/NoFrixion.MoneyMoov/Client/MoneyMoovApiClient.cs, src/NoFrixion.MoneyMoov/Enums/UserInviteStatusEnum.cs, src/NoFrixion.MoneyMoov/Models/User/UserInvite.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
Adds API client and methods for retrieving and sending user invites.
=> User invite client

src/NoFrixion.MoneyMoov/Api/UserInviteClient.cs, src/NoFrixion.MoneyMoov/Models/UserInvite/UserInviteCreate.cs
Passing invitee name from compliance portal which is required by the email template for invite in case of newly onboarded customer.
=> Passing invitee name

src/NoFrixion.MoneyMoov/Models/Payouts/PayoutsValidator.cs, test/MoneyMoov.UnitTests/Models/PayoutsValidatorTests.cs
Applying observations from testing with upstream supplier.
=> More adjustements for the payouts reference regex fields

src/NoFrixion.MoneyMoov/Api/UserInviteClient.cs, src/NoFrixion.MoneyMoov/Models/User/UserCreate.cs, src/NoFrixion.MoneyMoov/Models/UserInvite/UserInvite.cs, src/NoFrixion.MoneyMoov/Models/UserInvite/UserInviteCreate.cs
Added invitee first and last name to models as it was needed to pass the name from compliance portal.
=> New registration form changes

src/NoFrixion.MoneyMoov/Models/Statement/StatementHeader.cs, src/NoFrixion.MoneyMoov/Models/Transaction/Transaction.cs, src/NoFrixion.MoneyMoov/MoneyMoovApiEndPoints.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
Additional model, properties and methods to support the new API account statements.
=> New account statement changes

src/NoFrixion.MoneyMoov/Constants/PaymentsConstants.cs, src/NoFrixion.MoneyMoov/Enums/PaymentRequestEventTypesEnum.cs, src/NoFrixion.MoneyMoov/Enums/PaymentResultEnum.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPayment.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs
Added new event type and constants.
=> Added new event type and constants.

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs
Works proprely with the new post authorisation funds settlement mechanism.
=> Fix the Plaid PIS event authorisations

src/NoFrixion.MoneyMoov/Enums/MerchantTokenPermissionsEnum.cs, src/NoFrixion.MoneyMoov/Models/Token/MerchantToken.cs, src/NoFrixion.MoneyMoov/Models/Token/TokenAdd.cs
Added merchant token permissions enum
=> Merchant token permissions

src/NoFrixion.MoneyMoov/Api/PayoutClient.cs, src/NoFrixion.MoneyMoov/Api/RuleClient.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
Needed for new identity server feature.
=> Add client calls for get payout and rule objects.

src/NoFrixion.MoneyMoov/Models/Rules/Rule.cs, test/MoneyMoov.UnitTests/Models/RuleValidationTests.cs
This pull request adds a validation rule to ensure that a given Quartz cron expression runs at a frequency of at least **15** minutes. The `IsCronExpressionScheduledMoreThanXMinutes` function takes a cron expression string and a number of minutes, and returns true if the cron expression is scheduled to run at least every X minutes, or false otherwise.
Additionally, this pull request includes unit tests for the new validation rule to ensure it works as expected.
Changes Made
- Added a new function `IsCronExpressionScheduledMoreThanXMinutes` to validate the minimum period of a cron expression - schedule using the Quartz format.
- Added Unit tests for the new function.
=> Add validation rule for minimum period of cron schedule

src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs
Made userID nullable and added MerchantTokenDescription
=> Made userID nullable and added MerchantTokenDescription

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs
Fixed issue with wrong outstanding amount calculation. It was happening because of payments of 1 EURO.
=> Fixed issue with wrong outstanding amount calculation.

src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs
=> Add invoice ID field to payout.

src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
Removed obsolete transaction statement code
=> [MOOV-1451]: Removed obsolete transaction statement code

src/NoFrixion.MoneyMoov/Models/Beneficiary/Beneficiary.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutUpdate.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutsValidator.cs, test/MoneyMoov.UnitTests/Models/BeneficiarySerialisationTests.cs, test/MoneyMoov.UnitTests/Models/BeneficiaryValidationTests.cs
As per Wed design discussion.
Have obsoleted, rather than removed, redundant Payout* properties for now.
=> Model fixes to Payout and Beneficiary

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestMetrics.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutUpdate.cs
=> PaymentRequestMetrics

src/NoFrixion.MoneyMoov/Api/WebhookClient.cs, src/NoFrixion.MoneyMoov/Models/WebHook/Webhook.cs, src/NoFrixion.MoneyMoov/Models/WebHook/WebhookCreate.cs
Add webhook client and payload signature.
=> Client webhook

src/NoFrixion.MoneyMoov/Models/Merchant/Merchant.cs
Added list of accounts to merchant model.
=> Added list of accounts to merchant model

src/NoFrixion.MoneyMoov/Constants/PaymentsConstants.cs, src/NoFrixion.MoneyMoov/Enums/PaymentProcessorsEnum.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs
1.Added Nofrixion processor and provider id
2. Added pay by Nofrixion success event names in PaymentRequestResult
=> Added Nofrixion processor 

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestMinimal.cs
Added PispError property to PaymentRequestMinimal
=> Added PispError property to PaymentRequestMinimal

src/NoFrixion.MoneyMoov/Models/Merchant/MerchantPayByBankSetting.cs
Message property for banks table to make configurable messages.
=> Add message on Banks

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs
Added PriorityBankID to payment request.
=> Added PriorityBankID to payment request.

src/NoFrixion.MoneyMoov/Api/MoneyMoovApi.cs, src/NoFrixion.MoneyMoov/Api/PayoutClient.cs, src/NoFrixion.MoneyMoov/Client/MoneyMoovApiClient.cs, src/NoFrixion.MoneyMoov/Models/Payouts/BatchPayout.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs, test/MoneyMoov.IntegrationTests/MoneyMoovApiTests.cs
Includes methods to supprot batch payouts.
=> Add new payout client methods

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestMinimal.cs
Added PriorityBankID to PaymentRequestMinimal
=> Added PriorityBankID to PaymentRequestMinimal

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs, test/MoneyMoov.UnitTests/Models/PaymentRequestResultTests.cs
Added comment to clarfy use of PISP reference
=> Improved payment request attemtps logic to deal with orphaned settlement events

src/NoFrixion.MoneyMoov/Models/PaymentRequests/CardPaymentResponseStatus.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentAttempt.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs
Added card payment attempts to PaymentAttempts and exposed it as a property in PaymentRequest. I have not changed the logic in PaymentRequestResult to use PaymentAttempts yet. So it should not have an impact there.
=> Added card payment attempts to PaymentAttempts

src/NoFrixion.MoneyMoov/Enums/WalletsEnum.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestEvent.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentAttempt.cs
Added wallet name to payment attempt.
=> Added wallet name to payment attempt.

src/NoFrixion.MoneyMoov/Constants/PaymentRequestConstants.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestUpdate.cs
Moved validation regexes and messages from PaymentRequestCreate to a constants class and Added validations to PaymentRequestUpdate model.
=> Validations added to PaymentRequestUpdate model

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestMinimal.cs
Added StripeAccountID to Payment request minimal.
=> Added StripeAccountID to Payment request minimal.

src/NoFrixion.MoneyMoov/Constants/PaymentsConstants.cs, src/NoFrixion.MoneyMoov/Enums/PaymentRequestEventTypesEnum.cs, src/NoFrixion.MoneyMoov/Enums/PaymentResultEnum.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestEvent.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPayment.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentAttempt.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs, test/MoneyMoov.UnitTests/Models/PaymentRequestResultTests.cs
1. Added refund attempts in payment attempts.
2. Added refund cancelled event type.
3. In PaymentRequestResult, subtracting the refunded amount from amount paid so the status is managed automatically.
=> Added refund attempts

src/NoFrixion.MoneyMoov/ApiCients/PaymentRequestClient.cs, src/NoFrixion.MoneyMoov/ApiCients/PayoutClient.cs, src/NoFrixion.MoneyMoov/ApiCients/UserClient.cs, src/NoFrixion.MoneyMoov/ApiCients/UserInviteClient.cs, src/NoFrixion.MoneyMoov/ApiCients/WebhookClient.cs, src/NoFrixion.MoneyMoov/Enums/PaymentResultEnum.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentAttempt.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutsValidator.cs, src/NoFrixion.MoneyMoov/NoFrixion.MoneyMoov.csproj, src/NoFrixion.MoneyMoov/RestClient/RestApiResponse.cs
Property descriptions are currently missing from production swagger. This PR gets them abck in.
=> Fix XML comments so they show up in swagger file again.

src/NoFrixion.MoneyMoov/Attributes/CustomRegexString.cs, src/NoFrixion.MoneyMoov/Attributes/CustomRegexStringAttribute.cs
Created custom attribute to do regex check on string values
The default .NET RegularExpressionAttribute looks for a exact match on the regex.
=> Added validation for create merchant business associate names

src/NoFrixion.MoneyMoov/Enums/CurrencyTypeEnum.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestValidator.cs
Lightning will transaction in BTC, it doesn't need a separate currency.
=> Remove lightning bitcoin as a currency and add testnet bitcoin.

src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs
Fixed **PaymentRequestPaymentAttempt** `AuthorisedAt` and `AuthorisedAmount` fields not being correctly set for `AuthoriseOnly` payment requests.
=> [MOOV-1924]: Fixed Payment Attempt Authorisation field values

src/NoFrixion.MoneyMoov/Enums/PaymentResponseType.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/IPaymentResponse.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentInitiationRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentInitiationResponse.cs
Move some pisp related models to moneymoov.
Mark PaymentInitiationRequest.RedirectToOriginUrl as obsolete in favour of just OriginUrl.
=> Moov201 failurecallback 2

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs
Added AmountReceived, AmountRefunded and AmountPending auto-properties to the PaymentRequest model.
=> [MOOV-2070]: Added AmountReceived, AmountRefunded and AmountPending fields

src/NoFrixion.MoneyMoov/Models/Account/PaymentAccount.cs
Adds new balance fields to Accounts model.
=> Bc txsync 6

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestEmailNotification.cs, src/NoFrixion.MoneyMoov/NoFrixionProblem.cs, test/MoneyMoov.UnitTests/Mapping/CsvMapperTests.cs, test/MoneyMoov.UnitTests/Models/PaymentRequestEmailNotificationTests.cs
Enhances the batch file payment request create job to notify end customer of new payment request.
=> Add customer email notification models

src/NoFrixion.MoneyMoov/Mapping/CsvMapper.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs, test/MoneyMoov.UnitTests/Mapping/CsvMapperTests.cs
Add Tags options to payment request create so tags can be created on the fly.
=> Add tag values list option to payment request create.

src/NoFrixion.MoneyMoov/Models/User/UserMetrics.cs
=> Added user metrics model

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs
Added created by user and merchant token desc to Payment Request model
=> Added created by user and merchant token desc to Payment Request model

src/NoFrixion.MoneyMoov/Extensions/PaymentRequestEventExtensions.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/CardPaymentResponseStatus.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentAttempt.cs, test/MoneyMoov.UnitTests/Models/PaymentRequestExtensionTests.cs
Added failed card payment attempts to the PaymentRequest PaymentAttempts collection.
=> [MOOV-2174]: Added failure card payment attempts

src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
Added method to retrieve the bulk payout creation API endpoint URL.
=> [MOOV-2338]: Added BulkPayout endpoing URL method

src/NoFrixion.MoneyMoov/Models/Account/AccountTransactionMetrics.cs
Added AccountTransactionMetrics model.
=> Added AccountTransactionMetrics model.

src/NoFrixion.MoneyMoov/Models/Account/AccountTransactionMetrics.cs
Included number of payins and payouts in AccountTransactionMetrics model
=> Included number of payins and payouts in AccountTransactionMetrics model

src/NoFrixion.MoneyMoov/Models/Account/AccountMetrics.cs
=> Added account metrics model

src/NoFrixion.MoneyMoov/Enums/TimeFrequencyEnum.cs, src/NoFrixion.MoneyMoov/Models/Account/AccountMetrics.cs, src/NoFrixion.MoneyMoov/Models/Account/PeriodicBalance.cs
Added periodic balances properties to account metrics
=> Added periodic balances properties to account metrics

src/NoFrixion.MoneyMoov/Constants/PaymentsConstants.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentAmount.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs
Also added common PaymentAmount class so payreq and payout can share amount display logic.
=> Add a list of the authorisers who have already authorised to the payout model and views

src/NoFrixion.MoneyMoov/Claims/NoFrixionClaimsEnum.cs, src/NoFrixion.MoneyMoov/Enums/ApprovalTypesEnum.cs, src/NoFrixion.MoneyMoov/Enums/BeneficiaryAuthoriseStatusEnum.cs, src/NoFrixion.MoneyMoov/Enums/BeneficiaryEventTypeEnum.cs, src/NoFrixion.MoneyMoov/Models/Beneficiary/Beneficiary.cs, src/NoFrixion.MoneyMoov/Models/Beneficiary/BeneficiaryCreate.cs
- Separated BeneficiaryCreate model from Beneficiary model because Beneficiary model will contain Enabled flag.
- Added beneficiary specific claims for authorisation flow.
=> Added beneficiary claims and separated BeneficiaryCreate model from Beneficiary model

src/NoFrixion.MoneyMoov/ApiClients/BeneficiaryClient.cs, src/NoFrixion.MoneyMoov/ApiClients/MoneyMoovClient.cs, src/NoFrixion.MoneyMoov/Models/Beneficiary/Beneficiary.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
- Added beneficiary client to api clients
- Added account property to beneficiary model. This required to show details of account on identity server.
=> Added beneficiary client to api clients

src/NoFrixion.MoneyMoov/Enums/PayoutEventTypesEnum.cs, src/NoFrixion.MoneyMoov/Enums/UserRolesEnum.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutActivity.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutEvent.cs
1. Reordered UserRolesEnum in order of importance
2. Added Created, Queued and Scheduled to PayoutEventsTypesEnum
3. Added PayoutEvent model
=> Payout events

src/NoFrixion.MoneyMoov/Models/Beneficiary/Beneficiary.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutUpdate.cs
Replaced BeneficiaryID with BeneficiaryIdentifierID.
=> Replaced BeneficiaryID with BeneficiaryIdentifierID.

src/NoFrixion.MoneyMoov/Enums/BeneficiaryEventTypeEnum.cs, src/NoFrixion.MoneyMoov/Enums/PayoutEventTypesEnum.cs, src/NoFrixion.MoneyMoov/Models/Beneficiary/BeneficiaryEvent.cs, src/NoFrixion.MoneyMoov/Models/Beneficiary/BeneficiaryUpdate.cs
Added BeneficiaryUpdated event type and renamed AuthoriserID to UserID.
=> Added BeneficiaryUpdated event type and renamed AuthoriserID to UserID.

src/NoFrixion.MoneyMoov/Enums/BeneficiaryEventTypeEnum.cs, src/NoFrixion.MoneyMoov/Enums/PayoutEventTypesEnum.cs, src/NoFrixion.MoneyMoov/Models/Beneficiary/Beneficiary.cs
- Added BeneficiaryDisabled event type in payout and beneficiary
- Included Name and LastUpdated in calculation of approval hash.
=> Added BeneficiaryDisabled event type in payout and beneficiary

src/NoFrixion.MoneyMoov/Enums/BeneficiaryEventTypeEnum.cs, src/NoFrixion.MoneyMoov/Models/Approve/ApproveModel.cs
Added beneficiary enabled event type. This is required so updated properties can be determined in identity server from the last enabled or created event.
=> Added beneficiary enabled event type.

src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs
Add Simulator processor to the payment request attempt logic
=> Simluator attempt fix

src/NoFrixion.MoneyMoov/Models/Beneficiary/BeneficiaryUpdate.cs
=> Removed unused Method

src/NoFrixion.MoneyMoov/RestClient/RestApiClient.cs
Added PUT and DELETE overloads with concurrency token. This is needed for Banking circle PUT and DELETE operations.
=> Added PUT and DELETE overloads with concurrency token.

src/NoFrixion.MoneyMoov/Enums/PayoutEventTypesEnum.cs, src/NoFrixion.MoneyMoov/Enums/PayoutStatus.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutEvent.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutReject.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
Added new "RejectedApproval" payout status.
Also added a new URL endpoint builder for the new "Reject Payout" API endpoint.
=> [MOOV-2567]: Added new RejectedApproval payout status

src/NoFrixion.MoneyMoov/Extensions/PaymentRequestEventExtensions.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/CardPaymentResponseStatus.cs
Fixes the statuses for the CyberSruce void and refund responses.
=> CyberSource void status fix

src/NoFrixion.MoneyMoov/Extensions/PaymentAmount.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentSchedule.cs, src/NoFrixion.MoneyMoov/Models/Account/AccountIdentifier.cs
Some tweaks to display properties.
=> Authorise screen for payrun

src/NoFrixion.MoneyMoov/Models/Payruns/Payrun.cs
This PR introduces an update to the Payrun object model by adding a 'Status' property. This new property enables the API to return the current status of a payrun, providing clients with more detailed information.
- **New `Status` Property**: The Payrun object has been extended to include a 'Status' property.
=> Add `Status` Property to `Payrun` Object for Enhanced API Response

src/NoFrixion.MoneyMoov/Enums/PayrunStatus.cs
When a Payrun's payout is authorised PayrunPayoutAuthorised event Added PayoutsCreated to PayrunStatus
=> Added PayoutsCreated status to PayrunStatus

src/NoFrixion.MoneyMoov/Enums/ApprovalTypesEnum.cs
Added `Payrun` to the `ApproveTypesEnum`
=> Added Payrun to ApproveTypesEnum and handle in ApproveController.

src/NoFrixion.MoneyMoov/Models/Payouts/PayoutsValidator.cs, test/MoneyMoov.UnitTests/Models/PayoutsValidatorTests.cs
Added `GetYourReferenceFromInvoices`
Added `GetTheirReferenceFromInvoices`
=> Format references to include as many invoice refs as possible.

src/NoFrixion.MoneyMoov/Enums/PayrunEventTypeEnum.cs, src/NoFrixion.MoneyMoov/Models/Payruns/Payrun.cs, src/NoFrixion.MoneyMoov/Models/Payruns/PayrunEvent.cs
1. Added PayrunEventTypeEnum
2. Added PayrunEvent
=> [MOOV-2849] Payrun events

src/NoFrixion.MoneyMoov/Models/Payruns/Payrun.cs
Added Payouts to the Payrun model
=> [MOOV-2874] Payrun payouts

src/NoFrixion.MoneyMoov/Models/Payruns/Payrun.cs, src/NoFrixion.MoneyMoov/Models/Payruns/PayrunPayment.cs
Added `PayrunPayment` model to `Payrun` model
=> [MOOV-2874] Payrun payouts 2

src/NoFrixion.MoneyMoov/Constants/HttpClientConstants.cs, src/NoFrixion.MoneyMoov/Enums/PaymentProcessorsEnum.cs, src/NoFrixion.MoneyMoov/Enums/PaymentRequestEventTypesEnum.cs, src/NoFrixion.MoneyMoov/Enums/TransactionTypesEnum.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs
Adds shared functionality required for SEPA Direct Debit support.
=> MOOV-2736: Pay with SEPA Direct Debit

src/NoFrixion.MoneyMoov/Enums/PayoutEventTypesEnum.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs
Added `Signed` payout event type
Include the payout's id in the approval hash
=> [MOOV-2930] Payout signing

src/NoFrixion.MoneyMoov/Claims/ClaimsConstants.cs
Added constants for security setting claims
=> Added security settings claims to user.

src/NoFrixion.MoneyMoov/Enums/MerchantMandateStatusEnum.cs, src/NoFrixion.MoneyMoov/Enums/PaymentMethodTypeEnum.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentRequestPaymentAttemptExtensions.cs, src/NoFrixion.MoneyMoov/Models/Mandates/Mandate.cs, src/NoFrixion.MoneyMoov/Models/Mandates/MandateCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestEvent.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestResult.cs
Added support for Direct Debit payment attempts.
=> MOOV-2887: Added Direct Debit payment attempts

src/NoFrixion.MoneyMoov/Enums/PayrunEventTypeEnum.cs
Added Approved to PayrunEventTypeEnum so that mm4b can update it's state correctly.
=> [MOOV 2977] Payrun submitted

src/NoFrixion.MoneyMoov/Models/Approve/ApproveModel.cs
Added UserEmail to ApproveModel
=> Added UserEmail to ApproveModel

src/NoFrixion.MoneyMoov/Models/Account/AccountIdentifier.cs
=> Keep SCAN format consistent

src/NoFrixion.MoneyMoov/Models/Xero/XeroConnection.cs
=> Added Xero connection model

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestEvent.cs, src/NoFrixion.MoneyMoov/Models/Transaction/Transaction.cs
… different serialiser being used.
=> Minor fixes to tx and pay req event json model serialisation options

src/NoFrixion.MoneyMoov/Enums/ReportTypesEnum.cs
New report for merchant account information
=> Merchant accounts report type

src/NoFrixion.MoneyMoov/Enums/StatementGenerationStatusEnum.cs, src/NoFrixion.MoneyMoov/Enums/TransactionStatementFormat.cs, src/NoFrixion.MoneyMoov/Models/Statement/GenerateStatementRequest.cs, src/NoFrixion.MoneyMoov/Models/Statement/GenerateStatementResponse.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
Added various transaction statement models and members.
=> MOOV-3134: Added transaction statement models

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestAddress.cs
Added AddressCountryCode validation
=> Payment request shipping address fix

src/NoFrixion.MoneyMoov/Models/Rules/RuleEvent.cs
Added IsAuthoriseToEnable flag to RuleEvent model
=> Added IsAuthoriseToEnable flag to RuleEvent model

src/NoFrixion.MoneyMoov/Models/Rules/Rule.cs
Moved validation check from Rule model to respective handlers.
=> Handle trigger update

src/NoFrixion.MoneyMoov/Models/Rules/RuleUpdate.cs
For some reason the start at end at were not settable. Spent a lot of time trying to figure out why was date update not working.
=> Made dates settable

src/NoFrixion.MoneyMoov/Models/Rules/RuleUpdate.cs
Allow AccountID update on rule.
=> Allow AccountID update on rule.

src/NoFrixion.MoneyMoov/Mapping/CounterpartyMappers.cs, src/NoFrixion.MoneyMoov/Models/Account/AccountIdentifierCreate.cs, src/NoFrixion.MoneyMoov/Models/Account/CounterpartyCreate.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutUpdate.cs, src/NoFrixion.MoneyMoov/Models/Rules/Rule.cs, src/NoFrixion.MoneyMoov/Models/Rules/RuleActions/SweepAction.cs, src/NoFrixion.MoneyMoov/Models/Rules/RuleActions/SweepDestination.cs, src/NoFrixion.MoneyMoov/Models/Rules/RuleCreate.cs, src/NoFrixion.MoneyMoov/Models/Rules/RuleUpdate.cs, src/NoFrixion.MoneyMoov/Models/Transaction/Counterparty.cs, test/MoneyMoov.UnitTests/Models/RuleValidationTests.cs
Obsoletes redundant properties without breaking exiting models.
Add BeneficiaryID as a destination option for a counterparty.
=> Adjusts rule models

src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs
Added batchID to payout models
=> [MOOV-3224] Batch payouts

src/NoFrixion.MoneyMoov/Models/Rules/Rule.cs, src/NoFrixion.MoneyMoov/Models/Rules/RuleCreate.cs, src/NoFrixion.MoneyMoov/Models/Rules/RuleUpdate.cs
Option to set time zone id in cron rule
=> Option to set time zone id in cron rule

src/NoFrixion.MoneyMoov/Models/Beneficiary/Beneficiary.cs
Added last authorised date to beneficiary model.
=> Added last authorised date to beneficiary model.

src/NoFrixion.MoneyMoov/Extensions/JsonExtensions.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentRequestPaymentAttemptExtensions.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentAttempt.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPispSandboxCallback.cs, src/NoFrixion.MoneyMoov/MoneyMoovJson.cs
Adds an extra model for sandbox pay by bank simulations
=> Adds a dedicated method for determining payment request expiry

src/NoFrixion.MoneyMoov/Models/Merchant/Merchant.cs, src/NoFrixion.MoneyMoov/NoFrixionProblem.cs, src/NoFrixion.MoneyMoov/RestClient/RestApiClient.cs
Also minor fix to problem model to ensure status code is always set.
=> Add Modulr customer ID to merchant model

src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/Rules/RuleMinimal.cs, src/NoFrixion.MoneyMoov/Models/Transaction/Transaction.cs
Included rule details in payout and transaction models.
=> Return rule details in payout and transaction models.

src/NoFrixion.MoneyMoov/Models/Xero/XeroConnection.cs
Added tenant name to xero model
=> Added tenant name to xero model

src/NoFrixion.MoneyMoov/Models/Merchant/Merchant.cs
Added SupportedPaymentMethods field on Merchant class
=> MOOV-3293: Added SupportedPaymentMethods field on Merchant class

src/NoFrixion.MoneyMoov/Enums/XeroBankFeedSyncStatusEnum.cs, src/NoFrixion.MoneyMoov/Models/Account/PaymentAccount.cs
- Added Xero bank feed sync status enum
- Added xero bank feed properties to PaymentAccount model.
=> Xero bank feed sync status enum

src/NoFrixion.MoneyMoov/Models/Xero/XeroConnection.cs
Added real time connection property to XeroConnection model. This will help us determine whether the Xero connection in our db is still working or not i.e are we able to refresh tokens or not.
=> Real time Xero connection status.

src/NoFrixion.MoneyMoov/Models/Account/PaymentAccount.cs
Added rules minimal to payment account
=> Rules for an account

src/NoFrixion.MoneyMoov/Models/Account/PaymentAccount.cs
Added properties to the PaymentAccount model that are required for display purposes on MM4B.
=> Added Xero related properties for display on MM4B.

src/NoFrixion.MoneyMoov/Models/Account/PaymentAccount.cs
Made unsynchronised transaction count nullable
=> Made unsynchronised transaction count nullable

src/NoFrixion.MoneyMoov/Models/Xero/XeroConnection.cs
Added bank feed sync cron expression to connection properties. To be displayed on MM4B.
=> Added bank feed sync cron expression to connection properties

src/NoFrixion.MoneyMoov/Models/Xero/XeroConnection.cs
Added organisation short code to xero connection properties. Required for deep link.
=> Added organisation short code to xero connection properties.

src/NoFrixion.MoneyMoov/Claims/IdentityExtensions.cs, src/NoFrixion.MoneyMoov/Claims/NoFrixionClaimsEnum.cs
Added IsUsingPermissions claim check
=> Added IsUsingPermissions claim check

src/NoFrixion.MoneyMoov/Claims/IdentityExtensions.cs, src/NoFrixion.MoneyMoov/Permissions/Permissions.cs, test/MoneyMoov.UnitTests/Extensions/IdentityExtensionsTests.cs
Added an extension method to check if identity has some specific permissions for a specific merchant
=> Added an extension method to check if identity has some specific permissions for a specific merchant

src/NoFrixion.MoneyMoov/Models/Payouts/PayoutsDeleteResponse.cs
Model for batch payouts delete response.
=> Model for batch payouts delete response

src/NoFrixion.MoneyMoov/Extensions/PayrunStatusExtensions.cs, src/NoFrixion.MoneyMoov/Models/Payruns/Payrun.cs
Allow deletion of non-approved payruns.
=> Allow deletion of non-approved payruns.

src/NoFrixion.MoneyMoov/Enums/PayrunStatus.cs, src/NoFrixion.MoneyMoov/Models/Payruns/PayrunApprove.cs
Introduced intermediate state called "Queued"
=> Introduced intermediate state called "Queued"

src/NoFrixion.MoneyMoov/Models/User/UserRolePermissions.cs
Use a dictionary for MerchantPermissions and AccountPermissions
=> Simplified UserRolePermissions

src/NoFrixion.MoneyMoov/Enums/PayrunStatus.cs, src/NoFrixion.MoneyMoov/Extensions/PayrunStatusExtensions.cs
Removed the "Edited" payrun status in favor of "Draft".
=> Remove Edited payrun status

src/NoFrixion.MoneyMoov/Models/Roles/Role.cs, src/NoFrixion.MoneyMoov/Models/Roles/RoleCreate.cs, src/NoFrixion.MoneyMoov/Models/Roles/RoleUpdate.cs, src/NoFrixion.MoneyMoov/Models/User/UserRolePermissions.cs, src/NoFrixion.MoneyMoov/Permissions/Permissions.cs
Removed UserPermissions from roles model
=> [MOOV-3673] Permissions cleanup

src/NoFrixion.MoneyMoov/Enums/PaymentRailEnum.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutCreate.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutUpdate.cs
allow user choice between SEPA CT and Instant.
=> Add payment rail option to payout models to

src/NoFrixion.MoneyMoov/Constants/HttpClientConstants.cs
Added api client for tribe load and unload endpoints
=> Added api client for tribe load and unload endpoints

src/NoFrixion.MoneyMoov/Models/Payouts/PayoutsValidator.cs, test/MoneyMoov.UnitTests/Models/PayoutsValidatorTests.cs
Validate DestinationSortCode is 6 digits and DestinationAccountNumber is eight digits
=> Validate DestinationSortCode and DestinationAccountNumber

src/NoFrixion.MoneyMoov/Models/Payruns/Payrun.cs
Add IsArchived flag to the payrun model for use with MM4B.
=> MOOV-3637: Add IsArchived flag to the payrun model

src/NoFrixion.MoneyMoov/Enums/PayrunEventTypeEnum.cs
Added PayrunArchived and PayrunUnarchived event types.
=> MOOV-3719: Add Archived and Unarchived payrun event types

src/NoFrixion.MoneyMoov/Models/Account/PaymentAccount.cs
Adds an `IsArchived` property to the PaymentAccount model for use in MM4B.
=> MOOV-3537: Add IsArchived prop to PaymentAccount model

src/NoFrixion.MoneyMoov/Models/Mandates/Mandate.cs, src/NoFrixion.MoneyMoov/Models/Mandates/MandateCreate.cs
Changes the types of the Direct Debit mandate account number and sort code properties to strings.
=> MOOV-3743: Change DD mandate account number and sort code to string

src/NoFrixion.MoneyMoov/RestClient/RestApiClient.cs
Added support to pass custom headers and a different media type than json. Required for tribe api calls.
=> Added support for passing custom headers and media type

src/NoFrixion.MoneyMoov/Enums/WebhookResourceTypesEnum.cs, src/NoFrixion.MoneyMoov/Models/Tribe/TribeLoad.cs
Added a new resource type for TribeLoad and added a model that will be sent as the webhook payload.
=> Send tribe load failure webhook

src/NoFrixion.MoneyMoov/Models/Mandates/Mandate.cs, src/NoFrixion.MoneyMoov/Models/Mandates/MandateCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestEvent.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/NoFrixionProblem.cs
Fix bug where jsonproperty was being used instead of jsonignore 😊 .
=> Add DD mandate ID to payreq evt model. 

src/NoFrixion.MoneyMoov/CryptoHelper.cs, src/NoFrixion.MoneyMoov/Extensions/CurrencyExtensions.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentAmount.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/NonceHelper.cs
Aslo fixed the number of decimal places being used in the payout hash.
=> Adds nonce to Payout model

src/NoFrixion.MoneyMoov/Constants/PayrunConstants.cs, src/NoFrixion.MoneyMoov/Models/Payruns/PayrunInvoice.cs
Accept multiple emails for pay run. This is the only API change required.
=> Accept multiple emails for pay run

src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs
Added PayrunInvoices collection property to the Payout model.
=> MOOV-3823: Add PayrunInvoices collection to Payout model

src/NoFrixion.MoneyMoov/ApiClients/PayoutClient.cs, src/NoFrixion.MoneyMoov/HmacSignature/HmacAuthenticationConstants.cs, src/NoFrixion.MoneyMoov/HmacSignature/HmacSignatureAuthHelper.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs, src/NoFrixion.MoneyMoov/RestClient/RestApiClient.cs
Alos added new payout client method fpr TPP payout send.
=> Added HMAC signature from core assembly and added matching rest client overloads

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs
Fixed finished Direct Debit payment requests not having the correct AmountReceived.
=> MOOV-3873: Fix DD PaymentRequest AmountReceived

src/NoFrixion.MoneyMoov/Mapping/PayrunInvoiceMapper.cs, src/NoFrixion.MoneyMoov/Models/Payruns/PayrunInvoice.cs, test/MoneyMoov.UnitTests/Models/PayrunInvoiceValidatorTests.cs
- Renamed Reference to InvoiceReference to better differentiate it from PaymentReference
- Added a new nullable property called PaymentReference to Invoice model.
=> Invoice payment reference

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs
Reverts nofrixion/moneymoov-dotnet#453
=> Revert "Improve payment request success URL parsing."

src/NoFrixion.MoneyMoov/Permissions/Permissions.cs
Replaced CanCreateStatements & CanViewStatements with CanExportData permission
=> Updated statement permissions

src/NoFrixion.MoneyMoov/Models/User/User.cs
=> Remove user roles property

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs
Added a DestinationAccount property to the payment request "get" model.
=> MOOV-4015: Add DestinationAccount prop to payment request model

src/NoFrixion.MoneyMoov/Mapping/PayrunInvoiceMapper.cs, src/NoFrixion.MoneyMoov/Models/Payruns/PayrunInvoice.cs, test/MoneyMoov.UnitTests/Models/PayrunInvoiceValidatorTests.cs
Added counteryparty for invoice destination
=> Use counterparty for invoice destination

src/NoFrixion.MoneyMoov/Enums/AccountSepaInstantStatusEnum.cs, src/NoFrixion.MoneyMoov/Models/Account/PaymentAccount.cs
Add new `SupplierSepaInstantStatus` field and enum to the `Accounts` model.
=> MOOV-4018: Add Sepa Instant status field to Accounts entity

src/NoFrixion.MoneyMoov/Constants/RoleConstants.cs
Added a constant for all accounts scope for a role.
=> Roles assigned new template changes

src/NoFrixion.MoneyMoov/Models/Roles/UserRolesWithScope.cs
Createda minimal model that has the user role and scope on a merchant.
=> New roles send emails.

src/NoFrixion.MoneyMoov/Models/Roles/UserRolesWithScope.cs, src/NoFrixion.MoneyMoov/Models/User/User.cs
Removed AccountsCount property in favour of Scope which is a string. This is so the old roles scope can be set as "All accounts".
=> Added a Scope property 

src/NoFrixion.MoneyMoov/Models/Roles/UserRolesWithScope.cs
Added AssignedAt property to UserRoleWithScope model. This is required so we can show the JoinedAt date on the user profile in MM4B.
=> Added AssignedAt property to UserRoleWithScope model.

src/NoFrixion.MoneyMoov/Enums/AccountSepaInstantStatusEnum.cs
Added more SEPA Instant status values.
=> MOOV-3263: Additional Account SEPA Instant status values

src/NoFrixion.MoneyMoov/ApiClients/MerchantClient.cs, src/NoFrixion.MoneyMoov/ApiClients/MoneyMoovClient.cs, src/NoFrixion.MoneyMoov/ApiClients/TokensClient.cs, src/NoFrixion.MoneyMoov/Enums/AuthorisationType.cs, src/NoFrixion.MoneyMoov/Enums/MerchantTokenEventTypeEnum.cs, src/NoFrixion.MoneyMoov/Models/Token/MerchantToken.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs, src/NoFrixion.MoneyMoov/Permissions/Permissions.cs
Added authorise and archive merchant token API operations to the respective clients.
=> MOOV-3985: Add API calls for authorising merchant tokens

src/NoFrixion.MoneyMoov/Enums/TransactionTypesEnum.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentRequestEventExtensions.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs
Added `SEPA Direct Debit Rejection / Chargeback` as transaction type and mapped them to payment request refund attempts.
=> MOOV-4103: Handle SEPA Direct Debit Chargeback transactions

src/NoFrixion.MoneyMoov/Extensions/StringExtensions.cs
Moved ToSafeCsvString to StringExtensions.
=> Moved ToSafeCsvString to StringExtensions.

src/NoFrixion.MoneyMoov/Extensions/BeneficiaryExtensions.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentAccountExtensions.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs, src/NoFrixion.MoneyMoov/Extensions/PayoutExtensions.cs, src/NoFrixion.MoneyMoov/Models/Account/PaymentAccount.cs, src/NoFrixion.MoneyMoov/Models/Beneficiary/Beneficiary.cs, src/NoFrixion.MoneyMoov/Models/Export/IExportableToCsv.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestAddress.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/QueryResult.cs
Added ToCsv extension for exportable models
=> Added ToCsv extension for exportable models

src/NoFrixion.MoneyMoov/Extensions/PayoutExtensions.cs, src/NoFrixion.MoneyMoov/Extensions/StringExtensions.cs
=> Made ToSafeCsvString safer

src/NoFrixion.MoneyMoov/Mapping/AccountIdentifierMappers.cs, src/NoFrixion.MoneyMoov/Models/Account/AccountIdentifier.cs, src/NoFrixion.MoneyMoov/Models/Account/AccountIdentifierCreate.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/Payouts/PayoutsValidator.cs, src/NoFrixion.MoneyMoov/Models/Transaction/Counterparty.cs, test/MoneyMoov.UnitTests/Models/PayoutsValidatorTests.cs
=> Updated account identifier logic

src/NoFrixion.MoneyMoov/ApiClients/MerchantClient.cs, src/NoFrixion.MoneyMoov/Enums/UserInviteStatusEnum.cs, src/NoFrixion.MoneyMoov/Models/UserInvite/UserInvite.cs, src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
- Added new role API calls to MerchantClient.
- Added Accepted status to UserInvite model.
=> Compliance new role changes

src/NoFrixion.MoneyMoov/Models/User/ClientSessionTimeout.cs, src/NoFrixion.MoneyMoov/Models/User/User.cs
Expose min client session timeouts based on roles on merchant in User model.
=> Expose min client session timeouts based on roles on merchant

src/NoFrixion.MoneyMoov/Models/Merchant/MerchantSuspend.cs
Only contains optional `Reason`
=> Add `MerchantSuspend` object

src/NoFrixion.MoneyMoov/Claims/IdentityExtensions.cs, src/NoFrixion.MoneyMoov/Enums/MerchantTokenPermissionsEnum.cs
Added better description for merchant token identities.
=> Added new merchant token permissions for view accounts and payouts.

src/NoFrixion.MoneyMoov/Models/WebHook/Webhook.cs, src/NoFrixion.MoneyMoov/Models/WebHook/WebhookEvent.cs
Add merchant ID to webhook event model.
=> Add merchant ID to webhook event model.

src/NoFrixion.MoneyMoov/ApiClients/UserClient.cs, src/NoFrixion.MoneyMoov/HmacSignature/HmacSignatureBuilder.cs, src/NoFrixion.MoneyMoov/RestClient/RestApiClient.cs
Modified create user endpoint in UserClient to use secret.
=> Modified create user endpoint in UserClient to use secret

src/NoFrixion.MoneyMoov/Extensions/AmountMinorUnitExtensions.cs, src/NoFrixion.MoneyMoov/JsonConverters/DecimalConverter.cs, src/NoFrixion.MoneyMoov/JsonConverters/NumericConverter.cs, src/NoFrixion.MoneyMoov/Models/Account/PaymentAccount.cs, src/NoFrixion.MoneyMoov/Models/Payouts/Payout.cs, src/NoFrixion.MoneyMoov/Models/Transaction/Transaction.cs, src/NoFrixion.MoneyMoov/MoneyMoovJson.cs, test/MoneyMoov.UnitTests/Extensions/AmountMinorUnitExtensionsTests.cs, test/MoneyMoov.UnitTests/Json/NumericConverterTests.cs, test/MoneyMoov.UnitTests/Json/PaymentAccountSerialisationTests.cs, test/MoneyMoov.UnitTests/Json/PayoutSerialisationTests.cs, test/MoneyMoov.UnitTests/Json/TransactiontSerialisationTests.cs, test/MoneyMoov.UnitTests/XUnitLogger.cs
Added minor unit propreties to payment account, payout and transaction models.
=> Added json converters to always serialise monetary values with two decimal places

src/NoFrixion.MoneyMoov/Models/Beneficiary/BeneficiaryCreate.cs, src/NoFrixion.MoneyMoov/Models/Merchant/Merchant.cs
- Added an AccountCurrencies array prop to the merchant DTO that will be populated by all distinct currencies on the merchant's accounts.
- Added an AccountIdentifierType-to-Currency record mapping for beneficiary validation and creation.
=> MOOV-4194: Add AccountCurrencies to merchant object and USD beneficiary

src/NoFrixion.MoneyMoov/Constants/PaymentRequestConstants.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCustomField.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCustomFieldCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestMinimal.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentReceipt.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestUpdate.cs
Added custom fields and auto send receipt properties to payment requests
=> Custom fields in payment request and auto send receipt property

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCustomField.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCustomFieldCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestTemplate.cs
Added priority to custom fields. The fields have to be ordered when displaying on the UI.
=> Added priority to custom fields.

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCustomField.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCustomFieldCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestMinimal.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestUpdate.cs
Added template to minimal to determine the visibility of default fields on hosted payment page.
=> Use template for custom fields config where exists.

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentReceipt.cs
Added template to receipt model to decide visibility of default fields.
=> Added template to receipt model.

src/NoFrixion.MoneyMoov/Permissions/Permissions.cs
Added permissions to templates
=> Added permissions to templates

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestTemplate.cs
Included priority bank setting in default template.
=> Updated default template

src/NoFrixion.MoneyMoov/Enums/PaymentRequestPayerVisibleFieldsEnum.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestFieldDisplaySetting.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestMinimal.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestPaymentReceipt.cs
Added a property to payment request that will contain the display for payer config of default fields.
WIP: Using this config to decide visibility on the hosted payment page/receipts.
=> Added default field display settings to payment request.

src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequest.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestCreate.cs
Added notification role IDs to payment request.
=> Added notification role IDs to payment request.

src/NoFrixion.MoneyMoov/Models/Account/PaymentAccount.cs, src/NoFrixion.MoneyMoov/Models/Account/PaymentAccountCreate.cs, src/NoFrixion.MoneyMoov/Models/Statement/StatementHeader.cs
Added option to create trust accounts under merchant.
=> Added option to create trust accounts under merchant.

src/NoFrixion.MoneyMoov/ApiClients/MerchantClient.cs, src/NoFrixion.MoneyMoov/Models/Merchant/MerchantUpdate.cs
Added get merchant api to MerchantClient
=> Added get merchant api to MerchantClient

src/NoFrixion.MoneyMoov/Models/Beneficiary/Beneficiary.cs, src/NoFrixion.MoneyMoov/Models/Beneficiary/BeneficiaryCreate.cs, src/NoFrixion.MoneyMoov/Models/Beneficiary/BeneficiaryUpdate.cs
Added optional their reference property to beneficiary.
=> Added their reference to beneficiary

src/NoFrixion.MoneyMoov/Extensions/TransactionExtensions.cs, src/NoFrixion.MoneyMoov/Models/Transaction/Transaction.cs
Include payment request custom fields in transaction stmt csv and export csv
=> Include payment request custom fields in transaction stmt csv and export csv

src/NoFrixion.MoneyMoov/Constants/TimeZoneConstants.cs, src/NoFrixion.MoneyMoov/Extensions/DateTimeOffsetExtensions.cs
Extension method for DateTimeOffset to return time zone specific time
=> Extension method for DateTimeOffset to return time zone specific time

src/NoFrixion.MoneyMoov/Enums/RoleEventTypeEnum.cs, src/NoFrixion.MoneyMoov/Models/Roles/Role.cs, src/NoFrixion.MoneyMoov/Models/Roles/RoleEvent.cs
Add classes, properties and enums to support a new event log for role entities.
=> MOOV-4708: Add Events to Roles

src/NoFrixion.MoneyMoov/Extensions/PaymentRequestEventExtensions.cs, src/NoFrixion.MoneyMoov/Extensions/PaymentRequestExtensions.cs, src/NoFrixion.MoneyMoov/Models/PaymentRequests/PaymentRequestEvent.cs, test/MoneyMoov.UnitTests/Extensions/PaymentRequestExtensionsTests.cs
- Sorted by desc payment attempts initiated at date.
- Included payment method type to events.
=> Payment request model improvements.

src/NoFrixion.MoneyMoov/MoneyMoovUrlBuilder.cs
=> Batch user invites creation

src/NoFrixion.MoneyMoov/Models/Payouts/PayoutEvent.cs
Expose payee verification result in public model
=> Expose payee verification result in public model
